service: demo-serverless
 
provider:
  name: aws
  runtime: java11
  region: us-east-1
  memorySize: 1024
  timeout: 10
 
package:
  artifact: target/demo-serverless-1.0.0-shaded.jar
  
functions:
  saludo:
    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: saludo
